[package]
name = "http_header_types"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "headers"
harness = false

[dependencies]
bytes = "1.4.0"
chumsky = "1.0.0-alpha.3"
headers = "0.3.8"
http = "0.2.9"
logos = "0.13.0"
nom = "7.1.3"

[dev-dependencies]
criterion = "0.4.0"
